# Generated by Django 4.2.2 on 2024-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='payment',
            name='summ',
            field=models.PositiveIntegerField(default=0, verbose_name='сумма платежа'),
        ),
    ]
