# Generated by Django 4.2.2 on 2024-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_payment_payment_method_alter_payment_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='summ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='сумма платежа'),
        ),
    ]
