# Generated by Django 4.2.2 on 2024-09-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
        ('users', '0005_alter_payment_summ'),
    ]

    operations = [
    ]
