# Generated by Django 4.2.2 on 2024-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, help_text='укажите описание модуля', max_length=256, null=True, verbose_name='описание учебного модуля'),
        ),
    ]
