# Generated by Django 4.2.2 on 2024-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_alter_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='описание учебного модуля'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название модуля'),
        ),
    ]
