# Generated by Django 4.2.2 on 2024-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_alter_module_description_alter_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
    ]
