# Generated by Django 4.2.2 on 2024-09-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_remove_module_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='owner',
        ),
    ]
