# Generated by Django 4.2.2 on 2024-09-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_remove_course_created_at_remove_lesson_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название шага')),
                ('content', models.TextField(blank=True, null=True, verbose_name='контент шага')),
                ('ordering_number', models.PositiveSmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.lesson')),
            ],
            options={
                'verbose_name': 'шаг',
                'verbose_name_plural': 'шаги',
            },
        ),
    ]
