# Generated by Django 4.2.2 on 2024-09-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'учебный курс', 'verbose_name_plural': 'учебные курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['ordering_number'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['ordering_number'], 'verbose_name': 'учебный модуль', 'verbose_name_plural': 'учебные модули'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['ordering_number'], 'verbose_name': 'шаг', 'verbose_name_plural': 'шаги'},
        ),
    ]
