# Generated by Django 4.2.2 on 2024-09-08 09:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0011_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='контент шага'),
        ),
    ]
