# Generated by Django 4.2.2 on 2024-09-08 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_app', '0013_course_studying_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studying_users',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
