# Generated by Django 4.2.2 on 2024-09-12 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_app', '0016_step_steps_used_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='steps_used_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
